# Prevent Fastlane from overwriting README.md
app_identifier = 'io.tass.githubgrass'
publishing_match_certificate_repo = 'git@github.com:kuronekomichael/github-grass-certificates.git'

skip_docs

default_platform(:ios)

def suppress_output
  original_stdout, original_stderr = $stdout.clone, $stderr.clone
  $stderr.reopen File.new('/dev/null', 'w')
  $stdout.reopen File.new('/dev/null', 'w')
  yield
ensure
  $stdout.reopen original_stdout
  $stderr.reopen original_stderr
end

# これは、Flutterツールチェーンを使用して
#    flutter build ios --release --no-codesign
# を実行してアプリケーションを構築した後に、実行する必要があります。

# rebuild the app by:
# 1- Signing using the publishing credentials; and
# 2- xcodebuild with archive option

# このレーンでは、アプリのリビルドを行う
# PUBLISHING_MATCH_CERTIFICATE_REPO="git@github.com:kuronekomichael/github-grass-certificates.git"
# sigh_io.flutter.demo.gallery_appstore_profile-path=""
# 1. 
# This lane is meant to only rebuild the app by:
# 1- Signing using the publishing credentials; and
# 2- xcodebuild with archive option
platform :ios do

  desc 'Push a new release to TestFlight'
  lane :build_and_deploy_testflight do |options|
    #unlock

    # Doesn't do anything when not on Travis.
    setup_travis

    #get_certificates
    #get_provisioning_profile(adhoc: true, force: true)

    # Relative to this file.
    #raw_version = File.read('../../../../version')
    #puts "Building and deploying version #{raw_version}..."

    update_app_identifier(
      plist_path: 'Runner/Info.plist',
      # Let the checked-in bundle ID be different so users don't collide on
      # provisioning profile creation when building locally.
      app_identifier: app_identifier
    )

    #increment_version_number(
    #  # Only major, minor, patch digits and dots.
    #  version_number: /\d+\.\d+\.\d+/.match(raw_version)[0]
    #)

    puts 'Retrieving signing certificates and profiles...'
    # Stop fastlane from echoing back PUBLISHING_MATCH_CERTIFICATE_REPO var.
    #suppress_output {
      # Retrieves all the necessary certs and provisioning profiles.
      sync_code_signing(
        git_url: publishing_match_certificate_repo,
        type: 'appstore',  # 'adhoc' or 'appstore'
        readonly: true
      )
    #}
    puts 'Certificates and profiles installed'
  
    # Modify the Xcode project to use the new team and profile.
    # It will put the git state to dirty but Travis will be wiped after
    # then run session.
    disable_automatic_code_signing

    # see https://docs.fastlane.tools/actions/sigh/
    update_project_provisioning(
      xcodeproj: 'Runner.xcodeproj',
      target_filter: 'Runner',
      build_configuration: 'Release-Production',
      profile: ENV["sigh_#{app_identifier}_appstore_profile-path"],
    )

    # Build and archive the app again.
    # see [Gym](https://docs.fastlane.tools/actions/build_ios_app/)
    build_ios_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Production',
      configuration: 'Release-Production',
      export_method: 'app-store',
      codesigning_identity: 'iPhone Distribution: KOHKI NAKASHIMA (73J8ZXYZC6)',
    )

    if options[:upload]
      upload_to_testflight
    end
  end
end